# MySQL config
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST:localhost}:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
