version: "3"
services:
  mysqldb:
    image: mysql
    networks:
      - portfolio-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=portfolio_db
    ports:
      - "3306:3306"

  server:
    image: service-client
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_HOST: mysqldb
    restart: always
    networks:
      - portfolio-net
    depends_on:
      - mysqldb
    command: sh -c "/wait"

networks:
  portfolio-net: